const fs = require('fs');
const path = 'c:/Users/ovesk/watch-auction-marketplace/frontend/app/admin/page.js';
let content = fs.readFileSync(path, 'utf8');

const marker = '{/* User Detail Modal */}';
const idx = content.indexOf(marker);
if (idx === -1) { 
    console.error("Marker not found in " + path);
    process.exit(1); 
}

const head = content.substring(0, idx);

const tailLines = [
    '        {/* User Detail Modal */}',
    '        {selectedUser && (',
    '          <div className="fixed inset-0 z-[110] flex items-center justify-center p-4">',
    '             <div className="absolute inset-0 bg-slate-900/40 backdrop-blur-[2px]" onClick={() => setSelectedUser(null)}></div>',
    '             <div className="bg-white w-full max-w-4xl max-h-[90vh] rounded-2xl shadow-2xl relative z-10 overflow-hidden flex flex-col animate-in zoom-in-95 duration-400">',
    '                <div className="p-8 md:p-10 overflow-y-auto">',
    '                   <div className="flex justify-between items-start mb-10">',
    '                      <div className="flex items-center gap-6">',
    '                         <div className="w-16 h-16 rounded-xl bg-slate-50 border border-slate-100 flex items-center justify-center text-xl font-bold text-slate-400 shadow-sm">',
    '                            {selectedUser.user.name.charAt(0)}',
    '                         </div>',
    '                         <div>',
    '                            <h2 className="text-2xl font-bold text-slate-900 tracking-tight lowercase first-letter:uppercase">{selectedUser.user.name}</h2>',
    '                            <p className="text-[11px] font-medium text-slate-400 mt-1">{selectedUser.user.email}</p>',
    '                            <div className="flex gap-2 mt-3">',
    '                               <span className={`px-2 py-0.5 rounded text-[9px] font-bold uppercase tracking-wider ${selectedUser.user.role === "admin" ? "bg-slate-900 text-white" : "bg-slate-100 text-slate-500"}`}>{selectedUser.user.role}</span>',
    '                               {selectedUser.user.is_verified && <span className="px-2 py-0.5 bg-emerald-50 text-emerald-600 rounded text-[9px] font-bold uppercase tracking-wider border border-emerald-100">Verified</span>}',
    '                            </div>',
    '                         </div>',
    '                      </div>',
    '                      <button onClick={() => setSelectedUser(null)} className="p-2 hover:bg-slate-50 rounded-lg transition-colors text-slate-400">',
    '                        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">',
    '                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />',
    '                        </svg>',
    '                      </button>',
    '                   </div>',
    '',
    '                   <div className="grid grid-cols-1 md:grid-cols-3 gap-8">',
    '                      <div className="md:col-span-2 space-y-10">',
    '                         {/* Stats Row */}',
    '                         <div className="grid grid-cols-3 gap-4">',
    '                            <div className="p-5 bg-slate-50 rounded-xl border border-slate-100">',
    '                               <p className="text-[9px] font-bold text-slate-400 uppercase tracking-widest mb-1">Portfolio Value</p>',
    '                               <p className="text-lg font-bold text-slate-900">₹{(selectedUser.sellOrders || []).reduce((acc, curr) => acc + parseFloat(curr.product_price || 0), 0).toLocaleString()}</p>',
    '                            </div>',
    '                            <div className="p-5 bg-slate-50 rounded-xl border border-slate-100">',
    '                               <p className="text-[9px] font-bold text-slate-400 uppercase tracking-widest mb-1">Order Volume</p>',
    '                               <p className="text-lg font-bold text-slate-900">{(selectedUser.buyOrders || []).length}</p>',
    '                            </div>',
    '                            <div className="p-5 bg-slate-50 rounded-xl border border-slate-100">',
    '                               <p className="text-[9px] font-bold text-slate-400 uppercase tracking-widest mb-1">Active Assets</p>',
    '                               <p className="text-lg font-bold text-slate-900">{(selectedUser.products || []).length}</p>',
    '                            </div>',
    '                         </div>',
    '',
    '                         {/* Sections */}',
    '                         <div className="space-y-6">',
    '                            <h3 className="text-[10px] font-bold text-slate-400 uppercase tracking-[0.2em]">Asset Inventory</h3>',
    '                            <div className="space-y-3">',
    '                               {selectedUser.products.length === 0 ? (',
    '                                  <p className="text-[10px] font-medium text-slate-300 uppercase tracking-widest text-center py-12 bg-slate-50/50 rounded-xl border border-dashed border-slate-100">No active inventory records</p>',
    '                               ) : (',
    '                                  selectedUser.products.map(p => (',
    '                                     <div key={p.id} className="flex items-center gap-4 p-3 hover:bg-slate-50 transition-colors rounded-xl border border-transparent hover:border-slate-100">',
    '                                        <div className="w-10 h-10 bg-white rounded-lg border border-slate-100 overflow-hidden shrink-0">',
    '                                           <img src={getDisplayImage(p)} className="w-full h-full object-contain" />',
    '                                        </div>',
    '                                        <div className="flex-grow">',
    '                                           <p className="text-[11px] font-bold text-slate-900 truncate uppercase">{p.title}</p>',
    '                                           <p className="text-[9px] font-medium text-slate-400 uppercase mt-0.5 tracking-tight">Valuation: ₹{parseFloat(p.price).toLocaleString()}</p>',
    '                                        </div>',
    '                                        <span className={`px-2 py-0.5 rounded text-[8px] font-bold uppercase tracking-wider ${p.status === "approved" ? "bg-emerald-50 text-emerald-600" : "bg-amber-50 text-amber-600"}`}>{p.status}</span>',
    '                                     </div>',
    '                                  ))',
    '                               )}',
    '                            </div>',
    '                          </div>',
    '',
    '                          <div className="space-y-6 pt-6 border-t border-slate-100">',
    '                            <h3 className="text-[10px] font-bold text-slate-400 uppercase tracking-[0.2em]">Transaction History: Acquisitions</h3>',
    '                            <div className="space-y-3">',
    '                              {selectedUser.buyOrders?.length === 0 ? (',
    '                                <p className="text-[10px] font-medium text-slate-300 uppercase tracking-widest text-center py-8 bg-slate-50/50 rounded-xl border border-dashed border-slate-100">No acquisition records found</p>',
    '                              ) : (',
    '                                selectedUser.buyOrders?.map(o => (',
    '                                  <div key={o.id} className="flex items-center justify-between p-4 hover:bg-slate-50 transition-colors rounded-xl border border-transparent hover:border-slate-100">',
    '                                    <div className="flex flex-col gap-0.5">',
    '                                      <p className="text-[11px] font-bold text-slate-900 truncate uppercase">{o.title}</p>',
    '                                      <p className="text-[9px] font-medium text-slate-400 uppercase tracking-tight">Purchase ID #ORD-{(o.id || "N/A").toString().slice(-4)}</p>',
    '                                    </div>',
    '                                    <div className="text-right flex flex-col items-end gap-1">',
    '                                      <p className="text-[11px] font-bold text-slate-900 uppercase">₹{parseFloat(o.price || o.product_price || 0).toLocaleString()}</p>',
    '                                      <span className="px-2 py-0.5 rounded-[4px] text-[8px] font-bold uppercase tracking-wider bg-slate-100 text-slate-500 inline-block">{o.payment_status || "Paid"}</span>',
    '                                    </div>',
    '                                  </div>',
    '                                ))',
    '                              )}',
    '                            </div>',
    '                          </div>',
    '',
    '                          <div className="space-y-6 pt-6 border-t border-slate-100">',
    '                            <h3 className="text-[10px] font-bold text-slate-400 uppercase tracking-[0.2em]">Transaction History: Sales</h3>',
    '                            <div className="space-y-3">',
    '                              {selectedUser.sellOrders?.length === 0 ? (',
    '                                <p className="text-[10px] font-medium text-slate-300 uppercase tracking-widest text-center py-8 bg-slate-50/50 rounded-xl border border-dashed border-slate-100">No sales records found</p>',
    '                              ) : (',
    '                                selectedUser.sellOrders?.map(o => (',
    '                                  <div key={o.id} className="flex items-center justify-between p-4 hover:bg-slate-50 transition-colors rounded-xl border border-transparent hover:border-slate-100">',
    '                                    <div className="flex flex-col gap-0.5">',
    '                                      <p className="text-[11px] font-bold text-slate-900 truncate uppercase">{o.title}</p>',
    '                                      <p className="text-[9px] font-medium text-slate-400 uppercase tracking-tight">Sales ID #SAL-{(o.id || "N/A").toString().slice(-4)}</p>',
    '                                    </div>',
    '                                    <div className="text-right flex flex-col items-end gap-1">',
    '                                      <p className="text-[11px] font-bold text-emerald-600 uppercase">+₹{parseFloat(o.price || o.product_price || 0).toLocaleString()}</p>',
    '                                      <span className="px-2 py-0.5 rounded-[4px] text-[8px] font-bold uppercase tracking-wider bg-emerald-50 text-emerald-600 inline-block">Liquidated</span>',
    '                                    </div>',
    '                                  </div>',
    '                                ))',
    '                              )}',
    '                            </div>',
    '                          </div>',
    '                        </div>',
    '',
    '                      <div className="space-y-8 border-l border-slate-100 pl-8">',
    '                         <div>',
    '                            <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-5">Security Profile</p>',
    '                            <div className="space-y-5">',
    '                               <div>',
    '                                  <p className="text-[9px] font-bold text-slate-300 uppercase tracking-tight mb-1">Identity Verification</p>',
    '                                  <p className="text-xs font-bold text-slate-700">{selectedUser.user.phone || "Contact verification pending"}</p>',
    '                               </div>',
    '                               <div>',
    '                                  <p className="text-[9px] font-bold text-slate-300 uppercase tracking-tight mb-1">Member Since</p>',
    '                                  <p className="text-xs font-bold text-slate-700">{new Date(selectedUser.user.joined_date).toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" })}</p>',
    '                               </div>',
    '                            </div>',
    '                         </div>',
    '                         <div className="pt-8 border-t border-slate-100">',
    '                            <button ',
    '                               onClick={() => {',
    '                                 if (confirm("Proceed with account revocation? This action is logged.")) {',
    '                                   deleteUser(selectedUser.user.id);',
    '                                   setSelectedUser(null);',
    '                                 }',
    '                               }}',
    '                               className="w-full py-4 rounded-xl bg-white text-rose-600 text-[10px] font-bold uppercase tracking-widest hover:bg-rose-600 hover:text-white transition-all border border-rose-100 shadow-sm"',
    '                            >',
    '                               Revoke Account Access',
    '                            </button>',
    '                         </div>',
    '                      </div>',
    '                   </div>',
    '                </div>',
    '             </div>',
    '          </div>',
    '        )}',
    '',
    '        {/* Product Detail Modal */}',
    '        {selectedProduct && (',
    '          <div className="fixed inset-0 z-[110] flex items-center justify-center p-4">',
    '             <div className="absolute inset-0 bg-slate-900/40 backdrop-blur-[2px]" onClick={() => setSelectedProduct(null)}></div>',
    '             <div className="bg-white w-full max-w-4xl max-h-[90vh] rounded-2xl shadow-2xl relative z-10 overflow-hidden flex flex-col animate-in zoom-in-95 duration-400">',
    '                <div className="p-8 md:p-10 overflow-y-auto">',
    '                   <div className="flex justify-between items-start mb-8">',
    '                      <div className="flex items-center gap-6">',
    '                         <div className="w-20 h-20 rounded-xl bg-slate-50 border border-slate-100 p-2 overflow-hidden shrink-0 shadow-sm">',
    '                            <img src={getDisplayImage(selectedProduct)} className="w-full h-full object-contain" />',
    '                         </div>',
    '                         <div>',
    '                            <h2 className="text-2xl font-bold text-slate-900 tracking-tight uppercase">{selectedProduct.title}</h2>',
    '                            <p className="text-[11px] font-bold text-blue-600 mt-1 uppercase tracking-widest">{selectedProduct.category_name}</p>',
    '                            <div className="flex gap-3 mt-4">',
    '                               <span className="px-2 py-1 rounded text-[9px] font-bold uppercase tracking-wider bg-slate-900 text-white shadow-sm">₹{parseFloat(selectedProduct.price).toLocaleString()}</span>',
    '                               <span className={`px-2 py-1 rounded text-[8px] font-bold uppercase tracking-wider ${selectedProduct.status === "approved" ? "bg-emerald-50 text-emerald-600" : (selectedProduct.status === "pending" ? "bg-amber-50 text-amber-600" : "bg-rose-50 text-rose-600")}`}>',
    '                                  {selectedProduct.status || "pending"}',
    '                               </span>',
    '                            </div>',
    '                         </div>',
    '                      </div>',
    '                      <button onClick={() => setSelectedProduct(null)} className="p-2 hover:bg-slate-50 rounded-lg transition-colors text-slate-400">',
    '                        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">',
    '                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />',
    '                        </svg>',
    '                      </button>',
    '                   </div>',
    '',
    '                   <div className="grid grid-cols-1 md:grid-cols-3 gap-10">',
    '                      <div className="md:col-span-2 space-y-10">',
    '                         {/* Listing Metadata */}',
    '                         <div className="bg-slate-50/50 p-6 rounded-2xl border border-slate-100 flex items-center justify-between">',
    '                            <div>',
    '                               <p className="text-[9px] font-bold text-slate-400 uppercase tracking-widest mb-1">Authenticated Uploader</p>',
    '                               <p className="text-sm font-bold text-slate-900">{selectedProduct.seller_name || "System Admin"}</p>',
    '                            </div>',
    '                            <div className="text-right">',
    '                               <p className="text-[9px] font-bold text-slate-400 uppercase tracking-widest mb-1">Listing Date</p>',
    '                               <p className="text-sm font-bold text-slate-900">{new Date(selectedProduct.created_at).toLocaleDateString()}</p>',
    '                            </div>',
    '                         </div>',
    '',
    '                         {/* Description */}',
    '                         <div>',
    '                            <h3 className="text-[10px] font-bold text-slate-400 uppercase tracking-[0.2em] mb-4">Product Narrative</h3>',
    '                            <p className="text-[13px] text-slate-600 leading-relaxed font-medium bg-white p-6 rounded-2xl border border-slate-100">{selectedProduct.description || "No description provided."}</p>',
    '                         </div>',
    '',
    '                         {/* Technical Specs */}',
    '                         <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">',
    '                            <div>',
    '                               <h3 className="text-[10px] font-bold text-slate-400 uppercase tracking-[0.2em] mb-4">Mechanism & Build</h3>',
    '                               <div className="space-y-2">',
    '                                  {Object.entries(selectedProduct.item_specifics || {}).map(([key, val]) => (',
    '                                     !key.endsWith("_manual_mode") && (',
    '                                        <div key={key} className="flex justify-between p-3 bg-slate-50 rounded-lg">',
    '                                           <span className="text-[10px] font-bold text-slate-400 uppercase">{key.replace(/_/g, " ")}</span>',
    '                                           <span className="text-[10px] font-bold text-slate-900 uppercase">{String(val)}</span>',
    '                                        </div>',
    '                                     )',
    '                                  ))}',
    '                               </div>',
    '                            </div>',
    '                            <div>',
    '                               <h3 className="text-[10px] font-bold text-slate-400 uppercase tracking-[0.2em] mb-4">Certified Condition</h3>',
    '                               <div className="space-y-2">',
    '                                  <div className="flex justify-between p-3 bg-slate-50 rounded-lg border-l-2 border-slate-900">',
    '                                     <span className="text-[10px] font-bold text-slate-400 uppercase">Grade</span>',
    '                                     <span className="text-[10px] font-bold text-slate-900 uppercase font-black">{selectedProduct.condition_code}</span>',
    '                                  </div>',
    '                                  {Object.entries(selectedProduct.condition_details || {}).map(([key, val]) => (',
    '                                     !key.endsWith("_manual_mode") && (',
    '                                        <div key={key} className="flex justify-between p-3 bg-slate-50 rounded-lg">',
    '                                           <span className="text-[10px] font-bold text-slate-400 uppercase">{key.replace(/_/g, " ")}</span>',
    '                                           <span className="text-[10px] font-bold text-slate-900 uppercase">{String(val)}</span>',
    '                                        </div>',
    '                                     )',
    '                                  ))}',
    '                               </div>',
    '                            </div>',
    '                         </div>',
    '                      </div>',
    '',
    '                      <div className="space-y-8">',
    '                         <div>',
    '                            <h3 className="text-[10px] font-bold text-slate-400 uppercase tracking-[0.2em] mb-4">Gallery Assets</h3>',
    '                            <div className="grid grid-cols-2 gap-3">',
    '                               {(Array.isArray(selectedProduct.images) ? selectedProduct.images : (typeof selectedProduct.images === "string" ? JSON.parse(selectedProduct.images || "[]") : [])).map((img, index) => (',
    '                                  <div key={index} className="aspect-square rounded-xl border border-slate-100 overflow-hidden bg-slate-50">',
    '                                     <img src={`${API_BASE_URL}/uploads/${img}`} className="w-full h-full object-contain" />',
    '                                  </div>',
    '                               ))}',
    '                            </div>',
    '                         </div>',
    '                         ',
    '                         <div className="pt-8 border-t border-slate-100 flex flex-col gap-3">',
    '                            {selectedProduct.status !== "approved" && (',
    '                               <button ',
    '                                  onClick={() => { updateProductStatus(selectedProduct.id, "approved"); setSelectedProduct(null); }}',
    '                                  className="w-full py-4 bg-emerald-600 text-white rounded-xl text-[10px] font-bold uppercase tracking-widest shadow-lg shadow-emerald-100 hover:bg-emerald-700 transition-all font-sans"',
    '                               >',
    '                                  Authorize Listing',
    '                               </button>',
    '                            )}',
    '                            <button ',
    '                               onClick={() => { if(confirm("Permanently purge this record?")) { deleteProduct(selectedProduct.id); setSelectedProduct(null); } }}',
    '                               className="w-full py-4 bg-white text-rose-600 rounded-xl text-[10px] font-bold uppercase tracking-widest border border-rose-100 hover:bg-rose-600 hover:text-white transition-all font-sans"',
    '                            >',
    '                               Purge Inventory Record',
    '                            </button>',
    '                         </div>',
    '                      </div>',
    '                   </div>',
    '                </div>',
    '             </div>',
    '          </div>',
    '        )}',
    '      </div>',
    '    </div>',
    '  );',
    '}',
    ''
];

// Combine head and tail with actual newlines
fs.writeFileSync(path, head + tailLines.join('\\n'));
